[package]
name = "game"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.6.0", features = ["jpeg"] }
quick-protobuf = "0.8.0"
anyhow = "1.0.52"
approx = "0.4"
serde = "1.0"