[package]
name = "editor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
game = { path = "./../game"}
bevy_egui = "0.10"
bevy-inspector-egui = "0.7.3"

